### ISSUE TITLE
Publish on MELPA

### ISSUE THREAD

**Issue by kliph** [Kungsgeten/ink-mode#1]
Hi.  I came across your repo after I looked for an `ink-mode` on MELPA and did not find any packages.  If you're interested, I think more people would be inclined to use your code if it were published on MELPA.  Here's their [documentation on contributing](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.md) new packages.  

Please feel free to contact me if you need assistance with the publication.  I'd be happy to help.

Thanks for making this mode!

**Comment by Kungsgeten** [comment]
I'm sorry for the late reply (I'm on a holiday at the moment). I could add ink-mode to MELPA, but I'm not sure whether I'll continue working on it or not. My guess would be that the official ink editor is better suited, but on the other hand it is nice to write in Emacs.

I'll try to get in on MELPA next week or so :)

**Comment by wiseman** [comment]
I came to suggest the same thing, and found this issue already open.

**Comment by Kungsgeten** [comment]
I've just sent a pull request to MELPA, so hopefully ink-mode will be on there soon :)

**Comment by Kungsgeten** [comment]
The pull request has been accepted, so `ink-mode` will be on MELPA in a couple of hours. Thank you guys!
